title: Snow Stack 
description: 技術ブログ
# theme: minima  ← コメントアウト

# Minimal Mistakes を指定
remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap

locale: "ja-JP"

# Minimal Mistakes の設定
minimal_mistakes_skin: "default"  # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# サイト設定
author:
  name: "snow-stack"
  avatar: "/assets/images/snow-stack_mini.jpg"
  bio: "「雪塚」技術ブログ"
  location: "Sapporo, Japan"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/motoi-tsushima"

# デフォルト設定
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: home
      author_profile: false
      read_time: true
      comments: false
      share: false
      related: false